version: "2"
services:
  mergeframeworkserver:
    image: mergeframework
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - ./app/public:/var/www/app/public
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      SITE_URL: http://localhost
    networks:
      - impact
    restart: always

networks:
  impact:
    driver: bridge
